"use es6";

const { version } = require("../package.json");
export const VERSION = version;

export const messageType = {
  CALL_ANSWERED: "CALL_ANSWERED",
  CALL_COMPLETED: "CALL_COMPLETED",
  CALL_DATA: "CALL_DATA",
  CALL_ENDED: "CALL_ENDED",
  DIAL_NUMBER: "DIAL_NUMBER",
  END_CALL: "END_CALL",
  ENGAGEMENT_CREATED: "ENGAGEMENT_CREATED",
  ERROR: "ERROR",
  INCOMING_CALL: "INCOMING_CALL",
  INITIALIZED: "INITIALIZED",
  LOGGED_IN: "LOGGED_IN",
  LOGGED_OUT: "LOGGED_OUT",
  OUTGOING_CALL_STARTED: "OUTGOING_CALL_STARTED",
  READY: "READY",
  RESIZE_WIDGET: "RESIZE_WIDGET",
  SET_CALL_STATE: "SET_CALL_STATE",
  SET_WIDGET_URL: "SET_WIDGET_URL",
  SYNC_ACK_FAILED: "SYNC_ACK_FAILED",
  SYNC_ACK: "SYNC_ACK",
  SYNC: "SYNC",
  UNLOADING: "UNLOADING",
  USER_AVAILABLE: "USER_AVAILABLE",
  USER_UNAVAILABLE: "USER_UNAVAILABLE",
  VISIBILITY_CHANGED: "VISIBILITY_CHANGED",
  CREATE_ENGAGEMENT_SUCCEEDED: "CREATE_ENGAGEMENT_SUCCEEDED",
  CREATE_ENGAGEMENT_FAILED: "CREATE_ENGAGEMENT_FAILED",
};

export const errorType = {
  UNKNOWN_MESSAGE_TYPE: "UNKNOWN_MESSAGE_TYPE",
  GENERIC: "GENERIC",
};
